# Build on Push & Pull Request
name: Maven Build
on: 
  push:
    branches:
      ["release-4.*.*", "release-5.*.*", "release-v2.*.*", "master", "development","transformer_testing"]
  pull_request:
    branches:
      ["release-4.*.*", "release-5.*.*", "release-v2.*.*", "master", "development","transformer_testing"]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'temurin'
      
      - name: maven-settings-xml-action
        uses: whelk-io/maven-settings-xml-action@v20
        with:
          servers: >
            [
              {
                "id": "github-message-rosa",
                "username": "${env.GITHUB_USERNAME}",
                "password": "${env.GITHUB_TOKEN}"
              },
              {
                "id": "github-adapter",
                "username": "${env.GITHUB_USERNAME}",
                "password": "${env.GITHUB_TOKEN}"
              },
              {
                "id": "github-utils",
                "username": "${env.GITHUB_USERNAME}",
                "password": "${env.GITHUB_TOKEN}"
              },
              {
                "id": "github-dao",
                "username": "${env.GITHUB_USERNAME}",
                "password": "${env.GITHUB_TOKEN}"
              }
            ]
          output_file: $GITHUB_WORKSPACE/settings.xml
        env:
          GITHUB_USERNAME: ${{ secrets.USERNAME }}
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
      
      - name: Build and analyze
        env:
          GITHUB_USERNAME: ${{ secrets.USERNAME }}
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        run: mvn clean install -s $GITHUB_WORKSPACE/settings.xml -DskipTests
    
